# Bot-IoT DDoS Detection - Base Configuration
# Updated: 2025-10-05

# Random seed for reproducibility
random_seed: 42

# Data paths - NOW USING TEMPORAL SPLIT (5% sample)
paths:
  data_dir: "Data/processed/temporal_split_5pct"
  train_file: "train.csv"
  val_file: "val.csv"  # NEW: Validation set
  test_file: "test.csv"
  
  # Model artifacts
  models_dir: "models"
  results_dir: "results"
  experiments_dir: "experiments"
  artifacts_dir: "models/preprocessing_artifacts"

# Temporal configuration
temporal:
  enabled: true
  time_column: "stime"
  split_ratios:
    train: 0.7
    val: 0.15
    test: 0.15

# Data loading configuration
data_loading:
  chunksize: null  # Load all at once (null) or specify chunk size
  nrows: null      # Number of rows to load (null = all)
  usecols: null    # Columns to load (null = all)
  
# Logging
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
